UI Changes for Spiral Deadline
cmsc436/MS-app pull request #2
Opened 2017-02-14 04:41 UTC by DesAndrew

Increased font sizes. Implemented 3 trials for Tap Test.

2017-02-14 14:31 UTC, MrPickles commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_7" default="true" assert-keyword="true" jdk-15="true" project-jdk-name="1.8" project-jdk-type="JavaSDK">
Are these config changes necessary? Why were they changed?

2017-02-14 14:31 UTC, MrPickles commented on .idea/modules.xml
> +      <module fileurl="file://$PROJECT_DIR$/MS-app.iml" filepath="$PROJECT_DIR$/MS-app.iml" />
See comment from `misc.xml`.

2017-02-14 14:32 UTC, MrPickles commented on .idea/runConfigurations.xml
> +<?xml version="1.0" encoding="UTF-8"?>
See comment from `misc.xml`.

2017-02-14 14:32 UTC, MrPickles commented on .idea/vcs.xml
> -<?xml version="1.0" encoding="UTF-8"?>
Similarly, why was this removed?

2017-02-14 14:33 UTC, MrPickles commented on app/src/main/java/com/example/tapp/Record.java
> +                // Clear screen and set screen to waiting period.
Are all these case statements necessary? I'd imagine it'd be easier to reuse the case statements for each trial.

2017-02-14 14:43 UTC, DesAndrew commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_7" default="true" assert-keyword="true" jdk-15="true" project-jdk-name="1.8" project-jdk-type="JavaSDK">
I did not make this change manually, so I'm not sure why it was changed. However it appears that the only difference between the two lines is that the new line removed a '/' from the end

2017-02-14 14:45 UTC, DesAndrew commented on .idea/runConfigurations.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Same as above, not a manual change that I made, however, the line appears to have been moved from vcs.xml and placed here

2017-02-14 14:45 UTC, DesAndrew commented on .idea/vcs.xml
> -<?xml version="1.0" encoding="UTF-8"?>
See comment on runConfigurations.xml.

2017-02-14 14:47 UTC, DesAndrew commented on app/src/main/java/com/example/tapp/Record.java
> +                // Clear screen and set screen to waiting period.
While the separate case statements are ugly, I wanted to be able to provide different text prompts to the user each time, that way they didn't feel like they were looping over and over. Basically acknowledging to the user that they've done this before and want them to do it again.

2017-02-14 14:48 UTC, DesAndrew commented on .idea/modules.xml
> +      <module fileurl="file://$PROJECT_DIR$/MS-app.iml" filepath="$PROJECT_DIR$/MS-app.iml" />
I do not know what this change is, or where it came from (besides the fact that it clearly came from my push).

2017-02-20 01:24 UTC, jakrach commented on app/src/main/java/com/example/tapp/Record.java
> +                // Clear screen and set screen to waiting period.
I would recommend using a trial variable to keep count the trial and modify the text based on that, rather than having this convoluted logic.

2017-02-20 01:24 UTC, MrPickles requested changes
The image overlay looks good, although I'd really like for the trial logic to be simplified. It looks unnecessarily unwieldy in its current state.

2017-02-20 01:24 UTC, MrPickles commented on app/src/main/java/com/example/tapp/Spiral.java
> +
Image overlay looks good!

2017-02-21 02:23 UTC, krockpot approved these changes

2017-02-21 02:23 UTC, merged

2017-02-21 03:41 UTC, MrPickles commented on app/src/main/java/com/example/tapp/Record.java
> +                        " to tap as quickly as possible.\n" + hand + trial);
Watch out for debugging statements like this in the future. (You should have caught this when testing after you finished writing the code.) @DesAndrew

2017-02-21 08:32 UTC, DesAndrew commented on app/src/main/java/com/example/tapp/Record.java
> +                        " to tap as quickly as possible.\n" + hand + trial);
Damn, you're right, sorry about that.